/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProgressRouteImport } from './routes/_authed/progress'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedSnapNewRouteImport } from './routes/_authed/snap/new'
import { Route as AuthedSettingsStepsRouteImport } from './routes/_authed/settings/steps'
import { Route as AuthedJourneyHistoryRouteImport } from './routes/_authed/journey/history'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProgressRoute = AuthedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSnapNewRoute = AuthedSnapNewRouteImport.update({
  id: '/snap/new',
  path: '/snap/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsStepsRoute = AuthedSettingsStepsRouteImport.update({
  id: '/settings/steps',
  path: '/settings/steps',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJourneyHistoryRoute = AuthedJourneyHistoryRouteImport.update({
  id: '/journey/history',
  path: '/journey/history',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/progress': typeof AuthedProgressRoute
  '/journey/history': typeof AuthedJourneyHistoryRoute
  '/settings/steps': typeof AuthedSettingsStepsRoute
  '/snap/new': typeof AuthedSnapNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/progress': typeof AuthedProgressRoute
  '/journey/history': typeof AuthedJourneyHistoryRoute
  '/settings/steps': typeof AuthedSettingsStepsRoute
  '/snap/new': typeof AuthedSnapNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/progress': typeof AuthedProgressRoute
  '/_authed/journey/history': typeof AuthedJourneyHistoryRoute
  '/_authed/settings/steps': typeof AuthedSettingsStepsRoute
  '/_authed/snap/new': typeof AuthedSnapNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/progress'
    | '/journey/history'
    | '/settings/steps'
    | '/snap/new'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/progress'
    | '/journey/history'
    | '/settings/steps'
    | '/snap/new'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/progress'
    | '/_authed/journey/history'
    | '/_authed/settings/steps'
    | '/_authed/snap/new'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/progress': {
      id: '/_authed/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthedProgressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/snap/new': {
      id: '/_authed/snap/new'
      path: '/snap/new'
      fullPath: '/snap/new'
      preLoaderRoute: typeof AuthedSnapNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/steps': {
      id: '/_authed/settings/steps'
      path: '/settings/steps'
      fullPath: '/settings/steps'
      preLoaderRoute: typeof AuthedSettingsStepsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/journey/history': {
      id: '/_authed/journey/history'
      path: '/journey/history'
      fullPath: '/journey/history'
      preLoaderRoute: typeof AuthedJourneyHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProgressRoute: typeof AuthedProgressRoute
  AuthedJourneyHistoryRoute: typeof AuthedJourneyHistoryRoute
  AuthedSettingsStepsRoute: typeof AuthedSettingsStepsRoute
  AuthedSnapNewRoute: typeof AuthedSnapNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProgressRoute: AuthedProgressRoute,
  AuthedJourneyHistoryRoute: AuthedJourneyHistoryRoute,
  AuthedSettingsStepsRoute: AuthedSettingsStepsRoute,
  AuthedSnapNewRoute: AuthedSnapNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
