/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedArchivesRouteRouteImport } from './routes/_authenticated/archives/route'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedProgressIndexRouteImport } from './routes/_authenticated/progress/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChallengesIndexRouteImport } from './routes/_authenticated/challenges/index'
import { Route as AuthenticatedArchivesIndexRouteImport } from './routes/_authenticated/archives/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedChallengesNewRouteImport } from './routes/_authenticated/challenges/new'
import { Route as AuthenticatedApplicationsNewRouteImport } from './routes/_authenticated/applications/new'
import { Route as AuthenticatedSnapNewIndexRouteImport } from './routes/_authenticated/snap/new/index'
import { Route as AuthenticatedSettingsStepsIndexRouteImport } from './routes/_authenticated/settings/steps/index'
import { Route as AuthenticatedArchivesTodosIndexRouteImport } from './routes/_authenticated/archives/todos/index'
import { Route as AuthenticatedArchivesJourneysIndexRouteImport } from './routes/_authenticated/archives/journeys/index'
import { Route as AuthenticatedApplicationsApplicationIdIndexRouteImport } from './routes/_authenticated/applications/$applicationId.index'
import { Route as AuthenticatedApplicationsApplicationIdEditRouteImport } from './routes/_authenticated/applications/$applicationId.edit'
import { Route as AuthenticatedTeamsTeamIdMemberUserIdRouteImport } from './routes/_authenticated/teams/$teamId.member.$userId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchivesRouteRoute =
  AuthenticatedArchivesRouteRouteImport.update({
    id: '/archives',
    path: '/archives',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressIndexRoute =
  AuthenticatedProgressIndexRouteImport.update({
    id: '/progress/',
    path: '/progress/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengesIndexRoute =
  AuthenticatedChallengesIndexRouteImport.update({
    id: '/challenges/',
    path: '/challenges/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchivesIndexRoute =
  AuthenticatedArchivesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedArchivesRouteRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengesNewRoute =
  AuthenticatedChallengesNewRouteImport.update({
    id: '/challenges/new',
    path: '/challenges/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsNewRoute =
  AuthenticatedApplicationsNewRouteImport.update({
    id: '/applications/new',
    path: '/applications/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSnapNewIndexRoute =
  AuthenticatedSnapNewIndexRouteImport.update({
    id: '/snap/new/',
    path: '/snap/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsStepsIndexRoute =
  AuthenticatedSettingsStepsIndexRouteImport.update({
    id: '/settings/steps/',
    path: '/settings/steps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArchivesTodosIndexRoute =
  AuthenticatedArchivesTodosIndexRouteImport.update({
    id: '/todos/',
    path: '/todos/',
    getParentRoute: () => AuthenticatedArchivesRouteRoute,
  } as any)
const AuthenticatedArchivesJourneysIndexRoute =
  AuthenticatedArchivesJourneysIndexRouteImport.update({
    id: '/journeys/',
    path: '/journeys/',
    getParentRoute: () => AuthenticatedArchivesRouteRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdIndexRoute =
  AuthenticatedApplicationsApplicationIdIndexRouteImport.update({
    id: '/applications/$applicationId/',
    path: '/applications/$applicationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdEditRoute =
  AuthenticatedApplicationsApplicationIdEditRouteImport.update({
    id: '/applications/$applicationId/edit',
    path: '/applications/$applicationId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsTeamIdMemberUserIdRoute =
  AuthenticatedTeamsTeamIdMemberUserIdRouteImport.update({
    id: '/member/$userId',
    path: '/member/$userId',
    getParentRoute: () => AuthenticatedTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archives': typeof AuthenticatedArchivesRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/archives/': typeof AuthenticatedArchivesIndexRoute
  '/challenges/': typeof AuthenticatedChallengesIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/progress/': typeof AuthenticatedProgressIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/applications/$applicationId/edit': typeof AuthenticatedApplicationsApplicationIdEditRoute
  '/applications/$applicationId/': typeof AuthenticatedApplicationsApplicationIdIndexRoute
  '/archives/journeys/': typeof AuthenticatedArchivesJourneysIndexRoute
  '/archives/todos/': typeof AuthenticatedArchivesTodosIndexRoute
  '/settings/steps/': typeof AuthenticatedSettingsStepsIndexRoute
  '/snap/new/': typeof AuthenticatedSnapNewIndexRoute
  '/teams/$teamId/member/$userId': typeof AuthenticatedTeamsTeamIdMemberUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$token': typeof InviteTokenRoute
  '/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/archives': typeof AuthenticatedArchivesIndexRoute
  '/challenges': typeof AuthenticatedChallengesIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/progress': typeof AuthenticatedProgressIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/applications/$applicationId/edit': typeof AuthenticatedApplicationsApplicationIdEditRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdIndexRoute
  '/archives/journeys': typeof AuthenticatedArchivesJourneysIndexRoute
  '/archives/todos': typeof AuthenticatedArchivesTodosIndexRoute
  '/settings/steps': typeof AuthenticatedSettingsStepsIndexRoute
  '/snap/new': typeof AuthenticatedSnapNewIndexRoute
  '/teams/$teamId/member/$userId': typeof AuthenticatedTeamsTeamIdMemberUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/archives': typeof AuthenticatedArchivesRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/applications/new': typeof AuthenticatedApplicationsNewRoute
  '/_authenticated/challenges/new': typeof AuthenticatedChallengesNewRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/archives/': typeof AuthenticatedArchivesIndexRoute
  '/_authenticated/challenges/': typeof AuthenticatedChallengesIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/progress/': typeof AuthenticatedProgressIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/applications/$applicationId/edit': typeof AuthenticatedApplicationsApplicationIdEditRoute
  '/_authenticated/applications/$applicationId/': typeof AuthenticatedApplicationsApplicationIdIndexRoute
  '/_authenticated/archives/journeys/': typeof AuthenticatedArchivesJourneysIndexRoute
  '/_authenticated/archives/todos/': typeof AuthenticatedArchivesTodosIndexRoute
  '/_authenticated/settings/steps/': typeof AuthenticatedSettingsStepsIndexRoute
  '/_authenticated/snap/new/': typeof AuthenticatedSnapNewIndexRoute
  '/_authenticated/teams/$teamId/member/$userId': typeof AuthenticatedTeamsTeamIdMemberUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archives'
    | '/invite/$token'
    | '/applications/new'
    | '/challenges/new'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/applications/'
    | '/archives/'
    | '/challenges/'
    | '/dashboard/'
    | '/progress/'
    | '/teams/'
    | '/applications/$applicationId/edit'
    | '/applications/$applicationId/'
    | '/archives/journeys/'
    | '/archives/todos/'
    | '/settings/steps/'
    | '/snap/new/'
    | '/teams/$teamId/member/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$token'
    | '/applications/new'
    | '/challenges/new'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/applications'
    | '/archives'
    | '/challenges'
    | '/dashboard'
    | '/progress'
    | '/teams'
    | '/applications/$applicationId/edit'
    | '/applications/$applicationId'
    | '/archives/journeys'
    | '/archives/todos'
    | '/settings/steps'
    | '/snap/new'
    | '/teams/$teamId/member/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/archives'
    | '/invite/$token'
    | '/_authenticated/applications/new'
    | '/_authenticated/challenges/new'
    | '/_authenticated/teams/$teamId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/applications/'
    | '/_authenticated/archives/'
    | '/_authenticated/challenges/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/progress/'
    | '/_authenticated/teams/'
    | '/_authenticated/applications/$applicationId/edit'
    | '/_authenticated/applications/$applicationId/'
    | '/_authenticated/archives/journeys/'
    | '/_authenticated/archives/todos/'
    | '/_authenticated/settings/steps/'
    | '/_authenticated/snap/new/'
    | '/_authenticated/teams/$teamId/member/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archives': {
      id: '/_authenticated/archives'
      path: '/archives'
      fullPath: '/archives'
      preLoaderRoute: typeof AuthenticatedArchivesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress/': {
      id: '/_authenticated/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof AuthenticatedProgressIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/': {
      id: '/_authenticated/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof AuthenticatedChallengesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archives/': {
      id: '/_authenticated/archives/'
      path: '/'
      fullPath: '/archives/'
      preLoaderRoute: typeof AuthenticatedArchivesIndexRouteImport
      parentRoute: typeof AuthenticatedArchivesRouteRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges/new': {
      id: '/_authenticated/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof AuthenticatedChallengesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/new': {
      id: '/_authenticated/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof AuthenticatedApplicationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/snap/new/': {
      id: '/_authenticated/snap/new/'
      path: '/snap/new'
      fullPath: '/snap/new/'
      preLoaderRoute: typeof AuthenticatedSnapNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/steps/': {
      id: '/_authenticated/settings/steps/'
      path: '/settings/steps'
      fullPath: '/settings/steps/'
      preLoaderRoute: typeof AuthenticatedSettingsStepsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archives/todos/': {
      id: '/_authenticated/archives/todos/'
      path: '/todos'
      fullPath: '/archives/todos/'
      preLoaderRoute: typeof AuthenticatedArchivesTodosIndexRouteImport
      parentRoute: typeof AuthenticatedArchivesRouteRoute
    }
    '/_authenticated/archives/journeys/': {
      id: '/_authenticated/archives/journeys/'
      path: '/journeys'
      fullPath: '/archives/journeys/'
      preLoaderRoute: typeof AuthenticatedArchivesJourneysIndexRouteImport
      parentRoute: typeof AuthenticatedArchivesRouteRoute
    }
    '/_authenticated/applications/$applicationId/': {
      id: '/_authenticated/applications/$applicationId/'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId/'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$applicationId/edit': {
      id: '/_authenticated/applications/$applicationId/edit'
      path: '/applications/$applicationId/edit'
      fullPath: '/applications/$applicationId/edit'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$teamId/member/$userId': {
      id: '/_authenticated/teams/$teamId/member/$userId'
      path: '/member/$userId'
      fullPath: '/teams/$teamId/member/$userId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdMemberUserIdRouteImport
      parentRoute: typeof AuthenticatedTeamsTeamIdRoute
    }
  }
}

interface AuthenticatedArchivesRouteRouteChildren {
  AuthenticatedArchivesIndexRoute: typeof AuthenticatedArchivesIndexRoute
  AuthenticatedArchivesJourneysIndexRoute: typeof AuthenticatedArchivesJourneysIndexRoute
  AuthenticatedArchivesTodosIndexRoute: typeof AuthenticatedArchivesTodosIndexRoute
}

const AuthenticatedArchivesRouteRouteChildren: AuthenticatedArchivesRouteRouteChildren =
  {
    AuthenticatedArchivesIndexRoute: AuthenticatedArchivesIndexRoute,
    AuthenticatedArchivesJourneysIndexRoute:
      AuthenticatedArchivesJourneysIndexRoute,
    AuthenticatedArchivesTodosIndexRoute: AuthenticatedArchivesTodosIndexRoute,
  }

const AuthenticatedArchivesRouteRouteWithChildren =
  AuthenticatedArchivesRouteRoute._addFileChildren(
    AuthenticatedArchivesRouteRouteChildren,
  )

interface AuthenticatedTeamsTeamIdRouteChildren {
  AuthenticatedTeamsTeamIdMemberUserIdRoute: typeof AuthenticatedTeamsTeamIdMemberUserIdRoute
}

const AuthenticatedTeamsTeamIdRouteChildren: AuthenticatedTeamsTeamIdRouteChildren =
  {
    AuthenticatedTeamsTeamIdMemberUserIdRoute:
      AuthenticatedTeamsTeamIdMemberUserIdRoute,
  }

const AuthenticatedTeamsTeamIdRouteWithChildren =
  AuthenticatedTeamsTeamIdRoute._addFileChildren(
    AuthenticatedTeamsTeamIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchivesRouteRoute: typeof AuthenticatedArchivesRouteRouteWithChildren
  AuthenticatedApplicationsNewRoute: typeof AuthenticatedApplicationsNewRoute
  AuthenticatedChallengesNewRoute: typeof AuthenticatedChallengesNewRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRouteWithChildren
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedChallengesIndexRoute: typeof AuthenticatedChallengesIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedProgressIndexRoute: typeof AuthenticatedProgressIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedApplicationsApplicationIdEditRoute: typeof AuthenticatedApplicationsApplicationIdEditRoute
  AuthenticatedApplicationsApplicationIdIndexRoute: typeof AuthenticatedApplicationsApplicationIdIndexRoute
  AuthenticatedSettingsStepsIndexRoute: typeof AuthenticatedSettingsStepsIndexRoute
  AuthenticatedSnapNewIndexRoute: typeof AuthenticatedSnapNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchivesRouteRoute: AuthenticatedArchivesRouteRouteWithChildren,
  AuthenticatedApplicationsNewRoute: AuthenticatedApplicationsNewRoute,
  AuthenticatedChallengesNewRoute: AuthenticatedChallengesNewRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRouteWithChildren,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedChallengesIndexRoute: AuthenticatedChallengesIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedProgressIndexRoute: AuthenticatedProgressIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedApplicationsApplicationIdEditRoute:
    AuthenticatedApplicationsApplicationIdEditRoute,
  AuthenticatedApplicationsApplicationIdIndexRoute:
    AuthenticatedApplicationsApplicationIdIndexRoute,
  AuthenticatedSettingsStepsIndexRoute: AuthenticatedSettingsStepsIndexRoute,
  AuthenticatedSnapNewIndexRoute: AuthenticatedSnapNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
