/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedApplicationsRouteImport } from './routes/_authed/applications'
import { Route as AuthedTeamsIndexRouteImport } from './routes/_authed/teams/index'
import { Route as AuthedProgressIndexRouteImport } from './routes/_authed/progress/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedTeamsTeamIdRouteImport } from './routes/_authed/teams/$teamId'
import { Route as AuthedSnapNewRouteImport } from './routes/_authed/snap/new'
import { Route as AuthedSettingsStepsIndexRouteImport } from './routes/_authed/settings/steps/index'
import { Route as AuthedJourneyHistoryIndexRouteImport } from './routes/_authed/journey/history/index'
import { Route as AuthedTeamsTeamIdMemberUserIdRouteImport } from './routes/_authed/teams/$teamId.member.$userId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedApplicationsRoute = AuthedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedTeamsIndexRoute = AuthedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedProgressIndexRoute = AuthedProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTeamsTeamIdRoute = AuthedTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSnapNewRoute = AuthedSnapNewRouteImport.update({
  id: '/snap/new',
  path: '/snap/new',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsStepsIndexRoute =
  AuthedSettingsStepsIndexRouteImport.update({
    id: '/settings/steps/',
    path: '/settings/steps/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedJourneyHistoryIndexRoute =
  AuthedJourneyHistoryIndexRouteImport.update({
    id: '/journey/history/',
    path: '/journey/history/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedTeamsTeamIdMemberUserIdRoute =
  AuthedTeamsTeamIdMemberUserIdRouteImport.update({
    id: '/member/$userId',
    path: '/member/$userId',
    getParentRoute: () => AuthedTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof AuthedApplicationsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/snap/new': typeof AuthedSnapNewRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/progress/': typeof AuthedProgressIndexRoute
  '/teams/': typeof AuthedTeamsIndexRoute
  '/journey/history/': typeof AuthedJourneyHistoryIndexRoute
  '/settings/steps/': typeof AuthedSettingsStepsIndexRoute
  '/teams/$teamId/member/$userId': typeof AuthedTeamsTeamIdMemberUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof AuthedApplicationsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/snap/new': typeof AuthedSnapNewRoute
  '/teams/$teamId': typeof AuthedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/progress': typeof AuthedProgressIndexRoute
  '/teams': typeof AuthedTeamsIndexRoute
  '/journey/history': typeof AuthedJourneyHistoryIndexRoute
  '/settings/steps': typeof AuthedSettingsStepsIndexRoute
  '/teams/$teamId/member/$userId': typeof AuthedTeamsTeamIdMemberUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/applications': typeof AuthedApplicationsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/snap/new': typeof AuthedSnapNewRoute
  '/_authed/teams/$teamId': typeof AuthedTeamsTeamIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authed/progress/': typeof AuthedProgressIndexRoute
  '/_authed/teams/': typeof AuthedTeamsIndexRoute
  '/_authed/journey/history/': typeof AuthedJourneyHistoryIndexRoute
  '/_authed/settings/steps/': typeof AuthedSettingsStepsIndexRoute
  '/_authed/teams/$teamId/member/$userId': typeof AuthedTeamsTeamIdMemberUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/invite/$token'
    | '/snap/new'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/progress/'
    | '/teams/'
    | '/journey/history/'
    | '/settings/steps/'
    | '/teams/$teamId/member/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/dashboard'
    | '/invite/$token'
    | '/snap/new'
    | '/teams/$teamId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/progress'
    | '/teams'
    | '/journey/history'
    | '/settings/steps'
    | '/teams/$teamId/member/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/applications'
    | '/_authed/dashboard'
    | '/invite/$token'
    | '/_authed/snap/new'
    | '/_authed/teams/$teamId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authed/progress/'
    | '/_authed/teams/'
    | '/_authed/journey/history/'
    | '/_authed/settings/steps/'
    | '/_authed/teams/$teamId/member/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/applications': {
      id: '/_authed/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthedApplicationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/teams/': {
      id: '/_authed/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthedTeamsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/progress/': {
      id: '/_authed/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof AuthedProgressIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/teams/$teamId': {
      id: '/_authed/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthedTeamsTeamIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/snap/new': {
      id: '/_authed/snap/new'
      path: '/snap/new'
      fullPath: '/snap/new'
      preLoaderRoute: typeof AuthedSnapNewRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/steps/': {
      id: '/_authed/settings/steps/'
      path: '/settings/steps'
      fullPath: '/settings/steps/'
      preLoaderRoute: typeof AuthedSettingsStepsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/journey/history/': {
      id: '/_authed/journey/history/'
      path: '/journey/history'
      fullPath: '/journey/history/'
      preLoaderRoute: typeof AuthedJourneyHistoryIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/teams/$teamId/member/$userId': {
      id: '/_authed/teams/$teamId/member/$userId'
      path: '/member/$userId'
      fullPath: '/teams/$teamId/member/$userId'
      preLoaderRoute: typeof AuthedTeamsTeamIdMemberUserIdRouteImport
      parentRoute: typeof AuthedTeamsTeamIdRoute
    }
  }
}

interface AuthedTeamsTeamIdRouteChildren {
  AuthedTeamsTeamIdMemberUserIdRoute: typeof AuthedTeamsTeamIdMemberUserIdRoute
}

const AuthedTeamsTeamIdRouteChildren: AuthedTeamsTeamIdRouteChildren = {
  AuthedTeamsTeamIdMemberUserIdRoute: AuthedTeamsTeamIdMemberUserIdRoute,
}

const AuthedTeamsTeamIdRouteWithChildren =
  AuthedTeamsTeamIdRoute._addFileChildren(AuthedTeamsTeamIdRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedApplicationsRoute: typeof AuthedApplicationsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSnapNewRoute: typeof AuthedSnapNewRoute
  AuthedTeamsTeamIdRoute: typeof AuthedTeamsTeamIdRouteWithChildren
  AuthedProgressIndexRoute: typeof AuthedProgressIndexRoute
  AuthedTeamsIndexRoute: typeof AuthedTeamsIndexRoute
  AuthedJourneyHistoryIndexRoute: typeof AuthedJourneyHistoryIndexRoute
  AuthedSettingsStepsIndexRoute: typeof AuthedSettingsStepsIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedApplicationsRoute: AuthedApplicationsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSnapNewRoute: AuthedSnapNewRoute,
  AuthedTeamsTeamIdRoute: AuthedTeamsTeamIdRouteWithChildren,
  AuthedProgressIndexRoute: AuthedProgressIndexRoute,
  AuthedTeamsIndexRoute: AuthedTeamsIndexRoute,
  AuthedJourneyHistoryIndexRoute: AuthedJourneyHistoryIndexRoute,
  AuthedSettingsStepsIndexRoute: AuthedSettingsStepsIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
